### ISSUE TITLE
Sometime Fake_traffic doesn't work correctly

### ISSUE THREAD

**Issue by Doimatcuabautroi** [deedy5/fake_traffic#1]
Sometimes, Fake_traffic sends requests with false domains, as you can see the below image.
![fake](https://github.com/deedy5/fake_traffic/assets/18320809/d50a5ad2-c750-430c-8b15-465fc1b59e9d)

**Comment by deedy5** [comment]
fixed in [v1.9.0](https://github.com/deedy5/fake_traffic/releases/tag/v1.9.0)

**Comment by Doimatcuabautroi** [comment]
https://github.com/user-attachments/assets/e8de77a1-3b46-4d6f-9b8a-aa231df5f580
Fake_traffic doesn't work correctly again.
